# Generated by Django 5.0.2 on 2024-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snackbezorgd',
            name='completed',
        ),
        migrations.AddField(
            model_name='snackbezorgd',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
