# Generated by Django 5.0.2 on 2024-02-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0002_remove_snackbezorgd_completed_snackbezorgd_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snackbezorgd',
            new_name='product',
        ),
    ]
