# Generated by Django 5.0.2 on 2024-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0010_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernr', models.CharField(max_length=120)),
                ('name', models.TextField()),
                ('time', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paymentstatus', models.BooleanField(default=True)),
                ('total', models.BooleanField(default=True)),
            ],
        ),
    ]
