# Generated by Django 5.0.2 on 2024-03-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0011_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
