# Generated by Django 5.0.2 on 2024-03-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0012_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
