# Generated by Django 5.0.2 on 2024-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0013_alter_order_time_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
