# Generated by Django 5.0.2 on 2024-03-05 10:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0014_alter_order_name_alter_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentstatus',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordernr',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
