# Generated by Django 5.0.2 on 2024-03-05 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0015_rename_name_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ordernr',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
