# Generated by Django 5.0.2 on 2024-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0018_order_total_currency_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_currency',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
