# Generated by Django 5.0.2 on 2024-03-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0019_remove_order_total_currency_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
