# Generated by Django 5.0.2 on 2024-03-06 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0021_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
