# Generated by Django 5.0.2 on 2024-03-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snackbezorgd_app', '0022_product_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_number',
        ),
    ]
